language: haxe

haxe:
  - "3.4.7"
  - development

env:
  - REQUIREMENTS=requirements.txt         OUTDIR=coredep GENLIBS=docutils,pkgutil,inspect,importlib
  - REQUIREMENTS=requirements-externs.txt OUTDIR=out     GENLIBS=docutils,pkgutil,inspect,importlib,textwrap,numpy,scipy,pandas,matplotlib,seaborn,tensorflow,torch,theano,keras

sudo: required
dist: trusty

install:
  # xvfb
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # required by pyplot
  - sudo apt-get install libsm6 -y
  # use conda since pip install requires building libs which takes too much time
  # http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install psutil
  - conda config --add channels anaconda
  - conda config --add channels conda-forge
  - conda config --add channels pytorch
  - conda create -q --name pyextern --file $REQUIREMENTS python=3.6
  - source activate pyextern
  - conda env export
  # install haxelibs
  - yes | haxelib install build.hxml
  - haxelib list
  # build the generator
  - haxe build.hxml

script:
  - haxe test.hxml
  - python Main.py $GENLIBS $OUTDIR
