language: haxe

haxe:
  - "3.4.7"
  - development

env:
  - REQUIREMENTS="--file requirements.txt"          OUTDIR=coredep GENLIBS=docutils,pkgutil,inspect,importlib
  - REQUIREMENTS="--file requirements-externs.txt"  OUTDIR=out     GENLIBS=docutils,pkgutil,inspect,importlib,textwrap,numpy,scipy,pandas,matplotlib,seaborn,tensorflow,theano,keras
  - REQUIREMENTS="--file requirements-selenium.txt" OUTDIR=out     GENLIBS=selenium
  - REQUIREMENTS="--file requirements-pytorch.txt"  OUTDIR=out     GENLIBS=torch
  - REQUIREMENTS="--file requirements-qt.txt"       OUTDIR=out     GENLIBS=PyQt5,PySide2

sudo: required
dist: xenial
services:
  - xvfb

install:
  # required by pyplot
  - sudo apt-get install libsm6 -y
  # use conda since pip install requires building libs which takes too much time
  # http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install psutil
  - conda config --add channels anaconda
  - conda config --add channels conda-forge
  - conda config --add channels pytorch
  - conda create -q --name pyextern python=3.6 $REQUIREMENTS 
  - source activate pyextern
  - conda env export
  # install haxelibs
  - yes | haxelib install build.hxml
  - haxelib list
  # build the generator
  - haxe build.hxml

script:
  # Test the existing externs in the repo
  - haxe test.hxml
  # Test newly generated externs
  - python Main.py $GENLIBS $OUTDIR
  - haxe test.hxml
